// Finish the QIA pipeline run — create PR + update Jira
import { config } from 'dotenv';
import { Octokit } from '@octokit/rest';
import axios from 'axios';
config();

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const OWNER = process.env.GITHUB_OWNER;
const REPO = process.env.GITHUB_REPO;
const BRANCH = 'qia/scrum-5-2026-02-27T16-41-36';
const TICKET = 'SCRUM-5';
const JIRA_BASE = process.env.JIRA_BASE_URL;
const AUTH = 'Basic ' + Buffer.from(`${process.env.JIRA_EMAIL}:${process.env.JIRA_API_TOKEN}`).toString('base64');

// 1. Create PR
console.log(`\nCreating PR on ${OWNER}/${REPO}...`);
try {
  const pr = await octokit.rest.pulls.create({
    owner: OWNER,
    repo: REPO,
    title: `QIA: ${TICKET} — AI-generated tests`,
    body: `## QIA — AI-Generated Tests for ${TICKET}

> Auto-generated by QIA — Quality Intelligence Agent

### What's included
- \`src/framework/tests/ui/scrum-5-login.spec.ts\` (5 tests, ui)

### Test Coverage
- Framework DNA scanned and matched
- Self-healing locators (3-tier: testid → semantic → AI)
- GPT-4o powered strategy reasoning
- All 3 human gates approved

### CI
GitHub Actions will run 4 parallel shards automatically.

---
*Generated by QIA on ${new Date().toISOString()}*`,
    head: BRANCH,
    base: 'main',
  });
  console.log(`✅ PR created: ${pr.data.html_url}`);
} catch (e) {
  console.error('PR error:', e.status, e.message);
}

// 2. Update Jira — post comment
console.log(`\nPosting Jira comment on ${TICKET}...`);
try {
  await axios.post(`${JIRA_BASE}/rest/api/3/issue/${TICKET}/comment`, {
    body: {
      type: 'doc', version: 1,
      content: [{
        type: 'paragraph',
        content: [{ type: 'text', text: '🤖 QIA has generated automated tests for this ticket. Branch: ' + BRANCH + '. All 3 human gates approved. PR created on GitHub.' }]
      }]
    }
  }, { headers: { Authorization: AUTH, 'Content-Type': 'application/json' } });
  console.log(`✅ Jira comment posted on ${TICKET}`);
} catch (e) {
  console.error('Jira comment error:', e.response?.status, JSON.stringify(e.response?.data));
}

// 3. Transition Jira to Done
console.log(`\nTransitioning ${TICKET} to Done...`);
try {
  const transRes = await axios.get(`${JIRA_BASE}/rest/api/3/issue/${TICKET}/transitions`,
    { headers: { Authorization: AUTH } });
  const transitions = transRes.data.transitions;
  const done = transitions.find(t => t.name === 'Done');
  if (done) {
    await axios.post(`${JIRA_BASE}/rest/api/3/issue/${TICKET}/transitions`,
      { transition: { id: done.id } },
      { headers: { Authorization: AUTH, 'Content-Type': 'application/json' } });
    console.log(`✅ ${TICKET} → Done`);
  } else {
    console.log(`ℹ️  Available transitions: ${transitions.map(t => t.name).join(', ')}`);
  }
} catch (e) {
  console.error('Jira transition error:', e.response?.status, JSON.stringify(e.response?.data));
}

console.log('\n══════════════════════════════════════════');
console.log('  QIA RUN COMPLETE — SCRUM-5');
console.log('══════════════════════════════════════════\n');
